-- ============================================================
-- DMart Full Stack - MySQL Database Schema
-- Run this file in your MySQL client:
--   mysql -u root -p < schema.sql
-- ============================================================

CREATE DATABASE IF NOT EXISTS dmart_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE dmart_db;

-- ─── USERS ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    username    VARCHAR(80)  NOT NULL UNIQUE,
    email       VARCHAR(120) NOT NULL UNIQUE,
    password    VARCHAR(200) NOT NULL,
    is_admin    BOOLEAN DEFAULT FALSE,
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ─── CATEGORIES ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS categories (
    id    INT AUTO_INCREMENT PRIMARY KEY,
    name  VARCHAR(100) NOT NULL UNIQUE
);

-- ─── PRODUCTS ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS products (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    name         VARCHAR(150) NOT NULL,
    description  TEXT,
    price        DECIMAL(10,2) NOT NULL,
    stock        INT DEFAULT 0,
    image_url    VARCHAR(300),
    category_id  INT,
    created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

-- ─── ORDERS ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS orders (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    user_id      INT NOT NULL,
    total_price  DECIMAL(10,2) NOT NULL,
    status       ENUM('pending','confirmed','delivered','cancelled') DEFAULT 'pending',
    created_at   DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ─── ORDER ITEMS ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS order_items (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    order_id    INT NOT NULL,
    product_id  INT NOT NULL,
    quantity    INT NOT NULL,
    unit_price  DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (order_id)   REFERENCES orders(id)   ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- ─── CART ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS cart (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    user_id     INT NOT NULL,
    product_id  INT NOT NULL,
    quantity    INT DEFAULT 1,
    UNIQUE KEY unique_cart (user_id, product_id),
    FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- ─── SEED DATA ──────────────────────────────────────────────
INSERT IGNORE INTO categories (name) VALUES
    ('Fruits'), ('Drinks'), ('Curd & Milk'),
    ('Biscuits'), ('Chocolate'), ('Vegetables');

-- Admin user  (password = admin123  — bcrypt hash generated by app on first run)
-- You can register normally and then manually set is_admin=1 in MySQL:
--   UPDATE users SET is_admin=1 WHERE email='admin@dmart.com';

INSERT IGNORE INTO products (name, description, price, stock, image_url, category_id) VALUES
    ('Fresh Apples',      'Crisp red apples, 1 kg pack',         120.00, 50, 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400', 1),
    ('Bananas',           'Ripe yellow bananas, dozen',           40.00, 80, 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400', 1),
    ('Mango Juice',       'Tropicana mango juice, 1 L',           85.00, 40, 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400', 2),
    ('Coca Cola',         'Chilled Coca-Cola, 2 L bottle',        95.00, 60, 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400', 2),
    ('Full Cream Milk',   'Amul full cream milk, 1 L',            68.00, 30, 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400', 3),
    ('Dahi / Curd',       'Fresh homestyle curd, 500 g',          45.00, 25, 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=400', 3),
    ('Bourbon Biscuits',  'Britannia Bourbon cream, 200 g',       30.00, 100,'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400', 4),
    ('Marie Lite',        'Britannia Marie Lite, 250 g',          25.00, 90, 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400', 4),
    ('Dairy Milk',        'Cadbury Dairy Milk, 150 g',            75.00, 70, 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400', 5),
    ('Kit Kat',           'Nestle KitKat 4-finger bar',           50.00, 65, 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=400', 5),
    ('Tomatoes',          'Farm-fresh tomatoes, 500 g',           35.00, 45, 'https://images.unsplash.com/photo-1546470427-e26264be0b11?w=400', 6),
    ('Spinach',           'Tender baby spinach, 250 g',           28.00, 35, 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400', 6);
